# Bridges the phone call audio to and from the Gemini Live session over Twilio
# Media Streams. This file owns the phone connection and the audio bridge only.
#
# Under the Gemini Live design there is a single live session that hears the agent
# and speaks as the patient. This file's job is to carry audio between that session
# and the phone line: it sends the agent's incoming audio into the live session,
# and it sends the live session's generated patient audio back out over the call.
# It does not transcribe speech and it does not synthesize speech; the live session
# does both. This file just moves raw audio in both directions.

from typing import Awaitable, Callable


# A callback that receives one chunk of audio coming FROM the agent (the bytes the
# remote side is speaking). The pipeline wires this to the Gemini Live session so
# every chunk off the wire is fed straight into the live session as it arrives.
IncomingAudioHandler = Callable[[bytes], Awaitable[None]]

# A callback with no arguments that we call once, when the call has ended for any
# reason (agent hung up, we hung up, or the line dropped).
CallEndedHandler = Callable[[], Awaitable[None]]


class CallSession:
    """One live phone call, bridged to the Gemini Live patient session.

    This object represents a single call from the moment it is placed until it
    ends. The pipeline starts a call, registers a handler that forwards the
    agent's incoming audio into the Gemini Live session, and registers a handler
    to learn when the call ends. The patient's spoken audio, generated by the live
    session, is sent back to the agent through this same object. One CallSession is
    used for exactly one call.
    """

    def __init__(
        self,
        target_phone_number: str,
        twilio_account_sid: str,
        twilio_auth_token: str,
        twilio_from_number: str,
        media_stream_url: str,
    ) -> None:
        """Set up a call session, but do not place the call yet.

        Inputs:
            target_phone_number: the agent's phone number to dial, in E.164 form
                (for example "+18054398008").
            twilio_account_sid: the Twilio account id used to authenticate.
            twilio_auth_token: the Twilio auth token used to authenticate.
            twilio_from_number: the Twilio phone number the call is placed from.
            media_stream_url: the public websocket URL Twilio connects back to so
                audio can stream both ways (the "Media Streams" endpoint).

        Output:
            None. The call is started later by calling start_call.
        """
        # Steps the implementation will take:
        # 1. Store the phone numbers and credentials on the instance.
        # 2. Create the Twilio REST client from the sid and auth token.
        # 3. Prepare empty slots for the two handlers (incoming audio, call end)
        #    so they can be registered before the call starts.
        # 4. Prepare an empty slot for the active media stream connection.
        raise NotImplementedError(
            "CallSession.__init__ is a skeleton; wiring is not implemented yet."
        )

    def on_incoming_audio(self, handler: IncomingAudioHandler) -> None:
        """Register the function that receives audio coming from the agent.

        The pipeline points this at the Gemini Live session, so each chunk of the
        agent's speech is fed straight into the live session, which listens and
        decides the patient's reply.

        Input:
            handler: an async function we will call with each chunk of audio
                (raw bytes) that the agent speaks during the call.

        Output:
            None. The handler is stored and called repeatedly during the call.
        """
        # Steps the implementation will take:
        # 1. Save the handler so the media stream loop can call it per chunk.
        raise NotImplementedError(
            "CallSession.on_incoming_audio is a skeleton; not implemented yet."
        )

    def on_call_ended(self, handler: CallEndedHandler) -> None:
        """Register the function that runs once when the call ends.

        Input:
            handler: an async function we will call exactly one time, when the
                call finishes for any reason.

        Output:
            None. The handler is stored and called at end of call.
        """
        # Steps the implementation will take:
        # 1. Save the handler so the end-of-call logic can call it once.
        raise NotImplementedError(
            "CallSession.on_call_ended is a skeleton; not implemented yet."
        )

    async def start_call(self) -> None:
        """Place the outbound call and begin streaming audio.

        Input:
            None. Uses the numbers and credentials given at construction time.

        Output:
            None. This returns once the call is connected and audio is flowing.
            Audio from the agent arrives through the incoming-audio handler, which
            the pipeline has wired into the Gemini Live session.
        """
        # Steps the implementation will take:
        # 1. Ask Twilio to dial target_phone_number from twilio_from_number, and
        #    point the call at media_stream_url so audio streams to our websocket.
        # 2. Wait for the media stream websocket to connect.
        # 3. Start a loop that reads audio chunks from the websocket and passes
        #    each one to the registered incoming-audio handler (the live session).
        # 4. Watch for stream-stopped or hang-up signals and, when seen, call the
        #    registered call-ended handler exactly once.
        raise NotImplementedError(
            "CallSession.start_call is a skeleton; not implemented yet."
        )

    async def send_audio(self, audio_chunk: bytes) -> None:
        """Send one chunk of the patient's audio, from the live session, to the agent.

        The bytes here are the patient's spoken reply as generated by the Gemini
        Live session. This method writes them to the open call so the agent hears
        the patient.

        Input:
            audio_chunk: raw audio bytes produced by the live session (the
                patient's spoken reply) to play to the agent over the open call.

        Output:
            None. The bytes are written to the media stream so the agent hears
            them.
        """
        # Steps the implementation will take:
        # 1. Check that the media stream connection is open.
        # 2. Encode the chunk into the format Twilio Media Streams expects.
        # 3. Write the encoded chunk onto the websocket so the agent hears it.
        raise NotImplementedError(
            "CallSession.send_audio is a skeleton; not implemented yet."
        )

    async def hang_up(self) -> None:
        """End the call from our side.

        Input:
            None.

        Output:
            None. The call is closed and the call-ended handler is triggered.
        """
        # Steps the implementation will take:
        # 1. Tell Twilio to complete (end) the active call.
        # 2. Close the media stream websocket.
        # 3. Make sure the call-ended handler runs exactly once.
        raise NotImplementedError(
            "CallSession.hang_up is a skeleton; not implemented yet."
        )


def place_call(
    target_phone_number: str,
    twilio_account_sid: str,
    twilio_auth_token: str,
    twilio_from_number: str,
    media_stream_url: str,
) -> CallSession:
    """Build a ready-to-use call session for one outbound call.

    This is the simple front door other code uses. It creates a CallSession but
    does not dial yet, so the caller can register handlers first (wiring the
    incoming audio into the Gemini Live session) and then call start_call.

    Inputs:
        target_phone_number: the agent's number to dial, in E.164 form.
        twilio_account_sid: the Twilio account id.
        twilio_auth_token: the Twilio auth token.
        twilio_from_number: the Twilio number to place the call from.
        media_stream_url: the public websocket URL Twilio streams audio to.

    Output:
        A CallSession that is configured but has not started the call yet.
    """
    # Steps the implementation will take:
    # 1. Construct a CallSession with the given numbers and credentials.
    # 2. Return it so the caller can register handlers and then start the call.
    raise NotImplementedError("place_call is a skeleton; not implemented yet.")
